version: '3.9'
services:
  db:
    container_name: hotchpotch_db
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
  adminer:
    container_name: hotchpotch_adminer
    image: adminer:latest
    ports:
      - 8888:8080
    depends_on:
      - db

volumes:
  dbdata: null
